# Page settings
relativeURLs = true
uglyURLs = false
canonifyURLs = true
disablePathToLower = true

enableInlineShortcodes = true
baseURL = "https://warwick-igem-2021.github.io/"

title = "CREscent"
languageCode = "en-uk"
theme = "wiki-theme"


[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false



[menu]
    ### Project tab
    [[menu.main]]
        weight = 1
        identifier = "project"
        Name = "Project"
        URL = "#"
    [[menu.main]]
        weight = 2
        parent = "project"
        identifier = "description"
        Name = "Description"
        URL = "/Description"
    [[menu.main]]
        weight = 3
        parent = "project"
        identifier = "planning"
        Name = "Planning"
        URL = "/Planning"
    [[menu.main]]
        weight = 4
        parent = "project"
        identifier = "engineering"
        Name = "Engineering"
        URL = "/Engineering"
    [[menu.main]]
        weight = 5
        parent = "project"
        identifier = "model"
        Name = "Model"
        URL = "/Model"
    [[menu.main]]
        weight = 6
        parent = "project"
        identifier = "results"
        Name = "Results"
        URL = "/Results"
    [[menu.main]]
        weight = 7
        parent = "project"
        identifier = "contribution"
        Name = "Contributions"
        URL = "/Contribution"
        [[menu.main]]
        weight = 8
        parent = "project"
        identifier = "implementation"
        Name = "Implementation"
        URL = "/Implementation"

    ### Lab tab
    [[menu.main]]
        weight = 20
        identifier = "lab"
        Name = "Lab work"
        URL = "#"
    [[menu.main]]
        weight = 21
        parent = "lab"
        identifier = "proof_of_concept"
        Name = "Proof of concept"
        URL = "/Proof_Of_Concept"
    [[menu.main]]
        weight = 22
        parent = "lab"
        identifier = "experiments"
        Name = "Experiments"
        URL = "/Experiments"
    [[menu.main]]
        weight = 23
        parent = "lab"
        identifier = "parts"
        Name = "Parts"
        URL = "/Parts"
    [[menu.main]]
        weight = 24
        parent = "lab"
        identifier = "notebook"
        Name = "Notebook"
        URL = "/Notebook"
    [[menu.main]]
        weight = 25
        parent = "lab"
        identifier = "safety"
        Name = "Safety"
        URL = "/Safety"

    ### Human practices tab
    [[menu.main]]
        weight = 40
        identifier = "human_practices"
        Name = "Human practices"
        URL = "#"
    [[menu.main]]
        weight = 41
        parent = "human_practices"
        identifier = "overview"
        Name = "Human practices"
        URL = "/Human_Practices"
    [[menu.main]]
        weight = 42
        parent = "human_practices"
        identifier = "communication"
        Name = "Public engagement and education"
        URL = "/Communication"

    ### Team tab
    [[menu.main]]
        weight = 60
        identifier = "team"
        Name = "Team"
        URL = "#"
    [[menu.main]]
        weight = 61
        parent = "team"
        identifier = "about"
        Name = "Team"
        URL = "/Team"
    [[menu.main]]
        weight = 62
        parent = "team"
        identifier = "attributions"
        Name = "Attributions"
        URL = "/Attributions"
    [[menu.main]]
        weight = 63
        parent = "team"
        identifier = "collaborations"
        Name = "Collaborations"
        URL = "/Collaborations"
    [[menu.main]]
        weight = 64
        parent = "team"
        identifier = "sponsors"
        Name = "Sponsors"
        URL = "/Sponsors"

    ### Awards tab
    [[menu.main]]
        weight = 80
        identifier = "awards"
        Name = "Awards"
        URL = "#"
    [[menu.main]]
        weight = 81
        parent = "awards"
        identifier = "model_award"
        Name = "Model"
        URL = "/Model"
    [[menu.main]]
        weight = 82
        parent = "awards"
        identifier = "human_practices_award"
        Name = "Human practices"
        URL = "/Human_Practices"

    [[menu.main]]
        weight = 83
        parent = "awards"
        identifier = "sustainable"
        Name = "Sustainability"
        URL = "/Sustainable"
    [[menu.main]]
        weight = 84
        parent = "awards"
        identifier = "entrepreneurship"
        Name = "Entrepreneurship"
        URL = "/Entrepreneurship"

[params]

  # Meta
  author = "Warwick iGEM team 2021"
  description = "The wiki for the Warwick iGEM 2021 team entry"
  email = "igem@warwick.ac.uk"

  # Navigation section
  [params.navigation]
    # brand = "CREscent."
    brand_img = "/assets/images/logo.png"

  # Sidebar section
  [params.sidebar]
    logo_img = "/assets/images/logo_circle.png"

  # Hero section
  [params.hero]
    title = "CREscent to the moon"
    subtitle = "Fluorescent detection system for CRE"
    summary = "CREscent is our team's solution to combat CRE/CPE outbreaks in hospitals. It aims to be fast and efficient so that outbreaks can be prevented in advance."


  # Footer section
  [params.footer]
    copyright = '&copy; 2021 - Warwick iGEM CREscent, all rights reserved'
    content_license = 'Website content under <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" class="license-image" src="/assets/images/CC_BY_License.png"/></a>'
    theme_license = 'Website generator theme under <a rel="license" href="https://opensource.org/licenses/MIT"><img alt="MIT License" class="license-image" src="/assets/images/MIT_logo.svg" /></a>'

    twitter_url = "https://twitter.com/warwickigem"
    facebook_url = "https://www.facebook.com/WarwickIGEM"
    instagram_url = "https://www.instagram.com/igem_warwick"
    email_address = "mailto:igem@warwick.ac.uk"
    home_url = "https://warwick.ac.uk/"
