# Page settings
baseURL = "https://warwick-igem-2021.github.io/wiki.github.io/"
relativeURLs = true
uglyURLs = false
canonifyURLs = true

enableInlineShortcodes = true

title = "CREscent"
languageCode = "en-uk"
theme = "wiki-theme"





[menu]
    ### Project tab
    [[menu.main]]
        weight = 1
        identifier = "project"
        Name = "Project"
        URL = "#"
    [[menu.main]]
        weight = 2
        parent = "project"
        identifier = "about"
        Name = "About"
        URL = "/project/about"
    [[menu.main]]
        weight = 3
        parent = "project"
        identifier = "planning"
        Name = "Planning"
        URL = "/project/planning"
    [[menu.main]]
        weight = 4
        parent = "project"
        identifier = "design"
        Name = "Design"
        URL = "/project/design"
    [[menu.main]]
        weight = 5
        parent = "project"
        identifier = "models"
        Name = "Models"
        URL = "/project/models"
    [[menu.main]]
        weight = 6
        parent = "project"
        identifier = "results"
        Name = "Results"
        URL = "/project/results"
    [[menu.main]]
        weight = 7
        parent = "project"
        identifier = "contributions"
        Name = "Contributions"
        URL = "/project/contributions"

    ### Lab tab
    [[menu.main]]
        weight = 8
        identifier = "lab"
        Name = "Lab work"
        URL = "#"
    [[menu.main]]
        weight = 9
        parent = "lab"
        identifier = "proof_of_concept"
        Name = "Proof of concept"
        URL = "/lab/proof_of_concept"
    [[menu.main]]
        weight = 10
        parent = "lab"
        identifier = "experiments"
        Name = "Experiments"
        URL = "/lab/experiments"
    [[menu.main]]
        weight = 11
        parent = "lab"
        identifier = "parts"
        Name = "Parts"
        URL = "/lab/parts"
    [[menu.main]]
        weight = 12
        parent = "lab"
        identifier = "notebook"
        Name = "Notebook"
        URL = "/lab/notebook"
    [[menu.main]]
        weight = 13
        parent = "lab"
        identifier = "safety"
        Name = "Safety"
        URL = "/lab/safety"

    ### Human practices tab
    [[menu.main]]
        weight = 14
        identifier = "human_practices"
        Name = "Human practices"
        URL = "#"
    [[menu.main]]
        weight = 15
        parent = "human_practices"
        identifier = "overview"
        Name = "Overview"
        URL = "/human_practices/overview"
    [[menu.main]]
        weight = 16
        parent = "human_practices"
        identifier = "public_engagement_and_education"
        Name = "Public engagement and education"
        URL = "/human_practices/public_engagement_and_education"
    [[menu.main]]
        weight = 17
        parent = "human_practices"
        identifier = "sustainability"
        Name = "Sustainability"
        URL = "/human_practices/sustainability"
    [[menu.main]]
        weight = 18
        parent = "human_practices"
        identifier = "entrepreneurship"
        Name = "Entrepreneurship"
        URL = "/human_practices/entrepreneurship"

    ### Team tab
    [[menu.main]]
        weight = 19
        identifier = "team"
        Name = "Team"
        URL = "#"
    [[menu.main]]
        weight = 20
        parent = "team"
        identifier = "about"
        Name = "Team"
        URL = "/team/team"
    [[menu.main]]
        weight = 21
        parent = "team"
        identifier = "attributions"
        Name = "Attributions"
        URL = "/team/attributions"
    [[menu.main]]
        weight = 22
        parent = "team"
        identifier = "collaborations"
        Name = "Collaborations"
        URL = "/team/collaborations"
    [[menu.main]]
        weight = 23
        parent = "team"
        identifier = "sponsors"
        Name = "Sponsors"
        URL = "/team/sponsors"





[params]
  # Any additional css to include
  custom_css = []
  custom_js = []

  # Meta
  author = "Warwick iGEM team 2021"
  description = "The wiki for the Warwick iGEM 2021 team entry"
  email = "igem@warwick.ac.uk"

  # Navigation section
  [params.navigation]
    brand = "CREscent"

  # Hero section
  [params.hero]
    title = "CREscent"
    img = "images/logo.png"
    subtitle = "Easily identifying antibiotic resistant bacteria outbreaks before they can spread"


  # Footer section
  [params.footer]
    copyright = '&copy; Warwick iGEM 2021, all rights reserved - Source code available on <a href="https://github.com/Warwick-iGEM-2021/wiki.github.io">GitHub</a> - Powered by <a href="https://gohugo.io/">Hugo</a>'
    license = 'Website content licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ast">Creative Commons BY-SA-4.0 License</a>, and the theme under the <a href="https://opensource.org/licenses/MIT">MIT License</a>'
