# Page settings
baseurl = "https://warwick-igem-2021.github.io/wiki.github.io/"
relativeURLs = true
uglyURLs = false

title = "CREscent"
languageCode = "en-uk"
theme = "wiki-theme"



[menu]
    [[menu.main]]
        weight = 1
        identifier = "our-project"
        Name  = "Our project"
        # TODO: Fix this for push to github
        URL  = "./about"
    [[menu.main]]
        weight = 2
        parent = "our-project"
        identifier = "description"
        Name = "Description"
        URL = "#"
    [[menu.main]]
        weight = 3
        parent = "our-project"
        identifier = "results"
        Name = "Results"
        URL = "#"
    [[menu.main]]
        weight = 4
        identifier = "lab-work"
        Name  = "Lab work"
        URL  = "#"
    [[menu.main]]
        weight = 5
        parent = "lab-work"
        identifier = "modelling"
        Name  = "Modelling"
        URL  = "#"
    [[menu.main]]
        weight = 6
        parent = "lab-work"
        identifier = "wet lab"
        Name  = "Wet lab"
        URL  = "#"
    [[menu.main]]
        identifier = "human-practices"
        weight = 7
        Name  = "Human practices"
        URL  = "#"
    [[menu.main]]
        identifier = "timeline"
        weight = 8
        Name  = "Timeline"
        URL  = "./timeline"
    [[menu.main]]
        identifier = "team"
        weight = 9
        Name  = "Team"
        URL  = "./team"
    [[menu.main]]
        identifier = "awards"
        weight = 10
        Name  = "Awards"
        URL  = "#"



[params]
  # Any additional css to include
  custom_css = []
  custom_js = []

  # Meta
  author = "Warwick iGEM team 2021"
  description = "The wiki for the Warwick iGEM 2021 team entry"
  email = "igem@warwick.ac.uk"

  # Navigation section
  [params.navigation]
    brand = "CREscent"

  # Hero section
  [params.hero]
    title = "CREscent"
    img = "images/logo.png"
    subtitle = "Easily identifying antibiotic resistant bacteria outbreaks before they can spread"


  # Footer section
  [params.footer]
    copyright = '&copy; Warwick iGEM 2021, all rights reserved - Source code available on <a href="https://github.com/Warwick-iGEM-2021/wiki.github.io">GitHub</a> - Powered by <a href="https://gohugo.io/">Hugo</a>'
    license = 'Website content licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ast">Creative Commons BY-SA-4.0 License</a>, and the theme under the <a href="https://opensource.org/licenses/MIT">MIT License</a>'
